apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-exporter
  annotations: {}
spec:
  selector:
    matchLabels:
      app: name
  replicas: 3
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
        - name: container
          image: >-
            mkotelni/random-exporter:0.0.1
          ports:
            - containerPort: 8000
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
