apiVersion: v1
kind: Service
metadata:
  name: random-exporter
  labels:
    app: name
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    name: metrics
    protocol: TCP
    targetPort: 8000
  selector:
    app: name
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
